language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
    - rust: stable
      env: RUN=FMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt -- --check
script:
  - cargo test --features=test
